__title__ = 'Doc Chain'
__version__ = '4.6.3'
__build__ = 0x040603
__build_string__ = 'v4.6.3_Thu Mar 28 22:35:39 2024 -0400'
__django_version__ = '4.2'
__author__ = 'Docchain Team'
__author_email__ = 'hello@docchain.cloud'
__description__ = 'AI Enabled Electronic Document Management System'
__license__ = 'GPL 2.0'
__copyright_short__ = '2024 Docchain'
__copyright__ = '{} {}'.format('Copyright', __copyright_short__)
__website__ = 'https://www.docchain.cloud'
