# Generated by Django 4.2.11 on 2024-04-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0091_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_length', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
