# Generated by Django 4.2.11 on 2024-04-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0092_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocErrorHandling',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('doc_id', models.IntegerField()),
                ('ocr', models.BooleanField()),
                ('summary_file', models.BooleanField()),
            ],
        ),
    ]
