# Generated by Django 4.2.11 on 2024-04-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0093_docerrorhandling'),
    ]

    operations = [
        migrations.AddField(
            model_name='docerrorhandling',
            name='blockchain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='docerrorhandling',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='docerrorhandling',
            name='ocr',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='docerrorhandling',
            name='summary_file',
            field=models.BooleanField(default=False),
        ),
    ]
